### ISSUE TITLE
Zephyr won't connect if there is no headset plugged in

### ISSUE THREAD

**Issue by aaronp18** [ThomasGaubert/zephyr#128]
When I first tried Zephyr, it didn't connect at all, despite my best efforts. I then thought to retry it with my headset plugged in and it connected right away. 

I'm not sure if this is a bug or a limitation of the SteamVR API.

This isn't a huge problem, however it did seem like Zephyr wasn't working at all, so perhaps you could include a little warning / info alert that just tells the user that a headset must be plugged in order to connect. 

Keep up the good work :P

**Comment by ThomasGaubert** [comment]
Yup, this is a known issue. The overlay will fail to initialize if a headset isn't connected. This will prevent the server from starting.

Ideally the desktop interface would display an error but still run the server.

Thanks for the report!
