### ISSUE TITLE
Beta: Cannot find module 'electron-devtools-installer'

### ISSUE THREAD

**Issue by draeath** [ThomasGaubert/zephyr#133]
**Describe the bug**
PC side: Uncaught Exception "Cannot find module 'electron-devtools-installer'"

**To Reproduce**
1. Start Zephyr beta
2. Error immediately is presented
3. If OK is pressed, dialog closes and no further UI is shown (or in systray) but two zephyr processes remain running. Neither process is listening to TCP or UDP.

**Logs**
 No log file generated.

![image](https://user-images.githubusercontent.com/987449/80319880-f1f4d580-87e0-11ea-8f0c-3bc4932e284e.png)

**Desktop**
 - OS: Windows 10
 - Version 22.0.0.26274 / 2.0.0.2020042402 (from .exe details)
 - Beta: yes

**Comment by draeath** [comment]
Occurs in Canary (2.0.0.26277 / 2.0.0.202004245) as well.

**Comment by draeath** [comment]
Removed `%appdata%\Zephyr` and `%appdata%\zephyr-desktop`, uninstalled Zephyr itself (and ensured the application directory was removed) and reinstalled, no change in behavior. `%appdata%\Zephyr\logs` is recreated but no files are written.

**Comment by ThomasGaubert** [comment]
@draeath - Thanks for the report. I've rolled back the build to an older version which shouldn't be affected.

I'll have a proper fix and release it ASAP.

**Comment by ThomasGaubert** [comment]
Released an update (2.0.0.2020042701) which fixes this issue.
