### ISSUE TITLE
same device, multiple connections

### ISSUE THREAD

**Issue by kschima** [ThomasGaubert/zephyr#2]
Really needed this, so thanks for that :)

I tested a few times and got 5 device entries in the Desktop App, so receiving the same message 5 times.
After dis- and reconnecting with the mobile app, it seems I always get 2 device entries, so receiving the message 2 times.

At first start, I opened the Desktop App before starting SteamVR, the dashboard app appeared and notification worked when I started it the other way around.

Otherwise, great work!

**Comment by ThomasGaubert** [comment]
Thanks for the report! I thought I took care of this prior to release but I must have missed something.

I'll investigate and update here, but in the meantime can you provide the version of the Android app you're running?

**Comment by kschima** [comment]
1.0.4

**Comment by kschima** [comment]
Is fixed now. :)
