### ISSUE TITLE
Document the WebSocket API

### ISSUE THREAD

**Issue by r04r** [ThomasGaubert/zephyr#23]
Wiki documentation references the https://github.com/ThomasGaubert/zephyr/wiki/WebSocket-API page as the recommended way to interact with the API, but the page does not seem to exist.

**Comment by ThomasGaubert** [comment]
Yeah, unfortunately I haven't gotten to creating it yet. I'll get it up soon.

**Comment by ThomasGaubert** [comment]
The page has been [updated](https://github.com/ThomasGaubert/zephyr/wiki/WebSocket-API)!

Let me know if anything is unclear.
