### ISSUE TITLE
VirtualBox results in wrong IP address

### ISSUE THREAD

**Issue by ThomasGaubert** [ThomasGaubert/zephyr#26]
[Reported here.](https://www.reddit.com/r/zephyr_vr/comments/4x5l6c/zephyr_got_confused_by_virtualbox/)

Looks like Zephyr gets thrown off by other network devices, such as any virtual device installed by VirtualBox. Right now local IP address is grabbed naively (first non-internal address), but there might be a better way?

**Comment by r04r** [comment]
I can confirm experiencing this issue, but it does not actually seem a problem if you do know the correct address as Zephyr does seem to listen on all interfaces.

I'm not certain, but I don't think there's a good way to avoid this. A machine could legitimately have multiple network adapters and be part of multiple LANs at the same time. Uncommon, but very possible.

I think I've seen applications list all of the IP addresses before. But I'll definitely keep my eyes peeled to see if any better solutions pop up.

**Comment by ThomasGaubert** [comment]
Thanks for the second report! The solution I'll end up going with will be something along these lines.

**Comment by ThomasGaubert** [comment]
A fix for this issue will be pushed out later today.
