### ISSUE TITLE
Add Origin headers to overlay for CORS support.

### ISSUE THREAD

**Issue by dkoppel** [ThomasGaubert/zephyr#28]
It would be useful to add Origin headers to the responses from the RESTful API so that JS clients making requests from external resources can send notifications to the overlay, instead of having the cross-origin requests blocked by the browser: 

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:3753/. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

 I'm not super familiar with Socket.IO, cpp, or JS, but looking at the socketio docs, this looks pretty trivial.  I'll take a stab at it once I have a development env set up.  Thanks for this useful tool!

**Comment by dkoppel** [comment]
Implemented in commit a980f0c,  Thanks, works great!

**Comment by ThomasGaubert** [comment]
Awesome! 😄
