### ISSUE TITLE
Shut down old release pipeline

### ISSUE THREAD

**Issue by ThomasGaubert** [ThomasGaubert/zephyr#35]
With Zephyr's release on Steam, the AppVeyor CI and Heroku update server are no longer required and can be disabled.

The update server should stay up for ~1 month before being disabled to allow final updates (#36) to roll out to users.

**Comment by RichardRobertson** [comment]
So what's the situation on this Steam release?

**Comment by ThomasGaubert** [comment]
@RichardRobertson I ended up rewriting the project, so expect some movement in this area in the coming weeks. 😄

**Comment by ThomasGaubert** [comment]
1.x release pipeline has been shut down.
