### ISSUE TITLE
Steam beta test

### ISSUE THREAD

**Issue by ThomasGaubert** [ThomasGaubert/zephyr#37]
Distribute beta keys to users to ensure installation and operation works as expected.

See the [Version 2.0 beta milestone](https://github.com/ThomasGaubert/zephyr/milestone/1) for items required for the beta release.

**Comment by dkoppel** [comment]
I'd be happy to help in beta testing.

**Comment by ThomasGaubert** [comment]
@dkoppel Feel free to reach out on Reddit or Steam (TexasGamer for either) for a beta code.

**Comment by ThomasGaubert** [comment]
Re-opening this as this needs to be done again for v2.

**Comment by CaptainStouf** [comment]
Hi,
Is your request for v2 beta testers still valid ?

**Comment by ThomasGaubert** [comment]
Thanks for reaching out @CaptainStouf! Work is still (slowly) underway, so there's no beta quite yet. I'll post again once things are closer to launch.

**Comment by ThomasGaubert** [comment]
@dkoppel @CaptainStouf @gavinc I'm putting the final touches on the beta so please reach out to me on Reddit or Steam (TexasGamer on both) so I can send you Steam codes. Once I have the Android app available to download the testing can begin. 😄

Thanks for your patience leading up to this. It's been a *looooooong* time coming.

**Comment by ThomasGaubert** [comment]
Closing this as the beta is underway.
