### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by ChristophHaag** [ThomasGaubert/zephyr#38]
This project almost "just works" on Linux. I've done this:
https://github.com/ChristophHaag/zephyr/commit/5f6fd48909d0304ef98a4d5fec84cd2ce5e5d926
Adding submodules for the required projects and some other small fixes should be self explanatory.
I threw out the openvr libraries and header, because in my experience, only the actual OpenVR 1.0.6 interface works on Linux.

Some info on how to compile and run this stuff would be good. Like tl;dr:
* Go to zephyr/desktop/app, run `npm install`, with having electron installed run `electron .`
* Go to overlay/src, run qmake; make, run overlay/bin/win32/zephyr
* Run the android app and connect to the ip:port the desktop app displays

So, uhm... success I guess:
![zephyr2](https://cloud.githubusercontent.com/assets/781076/23834877/e293fd52-075d-11e7-8103-83ca3337bb63.png)

Only the overlay settings screen is just rendering garbage. Maybe that is because it's not been properly updated for the most recent OpenVR API? After all I had to replace `vr::API_OpenGL` with `vr::TextureType_OpenGL`, maybe other stuff needs to be changed too.

**Comment by ThomasGaubert** [comment]
Looks good! Right now I'm focusing on re-writing nearly everything for v2. Part of this includes cleaning up the (honestly terrible) overlay, updating to the latest OpenVR, and improving documentation.

Seeing how Linux support doesn't look to require too much additional work, I can look into officially supporting it with or soon after the v2 update.

**Comment by ThomasGaubert** [comment]
Closing this issue as it was already migrated to the new repository.
