### ISSUE TITLE
v2.0 Dismiss Notifications when Read

### ISSUE THREAD

**Issue by jhoff80** [ThomasGaubert/zephyr#55]
Just tried out the beta, it'd be nice to be able to dismiss notifications from the Zephyr overlay when I've read them in VR.  Preferably with a dismissal in VR also dismissing it on my phone, but either way it'd be nice to just clear out stuff when I've got a long list.  I only tried for a few minute but I couldn't seem to grab or click on any of the notifications in the history.

**Comment by ThomasGaubert** [comment]
@jhoff80 Good news! This just got shipped in the latest beta. You'll need to update both the desktop and Android app. Let me know if you run into any issues!
