### ISSUE TITLE
[v2] App crashes without connection set

### ISSUE THREAD

**Issue by matze19999** [ThomasGaubert/zephyr#58]
The android app for v2 crashes, when no connection settings are set and I click on the start button on the bottom.

Version: 2.0.0-beta-b45d554

**Comment by ThomasGaubert** [comment]
Weird, I'm not seeing a crash report on my end. Will investigate further.

**Comment by matze19999** [comment]
Me too. Can I send you a log file somehow.

**Comment by ThomasGaubert** [comment]
Reached out via email!
