### ISSUE TITLE
Google Hangouts onNotificationPosted firing on swipe notification removal

### ISSUE THREAD

**Issue by xhuytox** [ThomasGaubert/zephyr#6]
Because the event is fired on swipe notification removal, this causes a duplicate notification to be sent when the user goes to swipe away a notification on the phone. This seems to be isolated to Google Hangouts notifications as Gmail and Messenger (Google) did not do this. Not sure if it's a big enough deal to fix, but opening up the issue anyways. On debug, I did noticed that the notification that comes from the removal swipe has a notification.flag = 16 instead of the usual 17 that comes from when a Hangout notification appears.

**Comment by xhuytox** [comment]
Similar to https://github.com/ThomasGaubert/zephyr/issues/10, after restarting my phone, this issue doesn't happen anymore. Closing for now.

**Comment by ThomasGaubert** [comment]
Good to know! I'll keep an eye our for it (and the other issue) and possibly add logging to catch something like this in the future.
