### ISSUE TITLE
v2.0 Android app setup feedback

### ISSUE THREAD

**Issue by lestaticon** [ThomasGaubert/zephyr#60]
Android app version:
2.0.0-beta-b45d554

**v2.0 Android app setup feedback**

I'm sure it varies how "noisy" any particular phone may be if all notifications are enabled in Zephyr by default. I wonder if it makes sense to automatically display the notification management screen upon first run? Personally, as soon as I opened the freshly installed app, and before joining/pairing or doing anything else, I found and opened the Manage notifications settings as I naturally wanted control over what notifications are accessed. I immediately disabled all via the sub menu then manually enabled a select few apps. As a more technical user, I had no trouble doing any of this and am only glad you decided to include these settings. However, thinking about the less technical users, they might have a hard time even thinking to look for these settings or even finding the menu option to disable all at once. Considering how crowded some users phones may be with apps, having them all enabled might annoy a less savvy user (whereas a more technical user might then think to look for the notification management settings to suppress less useful notifications).

About device:
Android version 9
Moto Z3 Play

**Comment by ThomasGaubert** [comment]
Good call 👍 Showing some sort of prompt after notification access has been granted would make that process go much smoother.

**Comment by lestaticon** [comment]
Thanks for letting me test it out! Here is also some general feedback along these lines; the current level of polish and the overall decisions you've made speak volumes about your design skill and it was very much appreciated from a user standpoint. It was refreshing to be able to access, essentially, what I wanted without having to think about where some setting/action/feature might be buried or have to weed through unnecessarily creative names for common things. I also really like the notifications management and the general UI choices you've made (toggles, colors, placement of menus)

Also, the documentation seemed to be well written, clear, and organized.

**Comment by ThomasGaubert** [comment]
Thanks! It means a lot 😄

**Comment by ThomasGaubert** [comment]
Closing as this was addressed a while back and I forgot to close this issue.
