### ISSUE TITLE
v2.0 Android app suggestion regarding the persistent notification and shutting down

### ISSUE THREAD

**Issue by lestaticon** [ThomasGaubert/zephyr#62]
Android app version:
2.0.0-beta-b45d554

v2.0 Android app 

I have one more suggestion based upon some behavior I saw while using the system. 

First, the behavior:
If the SteamVR-Zephry-server app is running and I load up the Zephry-android app, the notification showing the status of the connection stays persistent even if I toggle the android app connection off in the UI. (pressing the blue Stop)

I'm sure this is by design, however, when I dismiss the app from the android system (open the app history and dismiss it) the notification remains and is not something I can swipe to dismiss. 

Personally, and take this as just an opinion, I would like to see an "exit" menu option which then kills the app and shuts down any supporting process. Maybe something to put inside the menu and not on the main app face to prevent users from closing it by mistake. 

I don't think this is an issue if the desktop app has been shut down. The notification doesn't remain persistent if the android app cannot connect (it seems). 

So this is really just a usability suggestion and not really critical (to me). Though, I could see some less savvy users being irritated by the persistent notification if they do not get what is going on. I'm only guessing you need that notification to keep the connection alive or make it more reliable? If not, I would even consider getting rid of that. I always kept the app in focus and went back to it when ready to stop using it. I never used the notification. 

About device:
Android version 9
Moto Z3 Play

**Comment by lestaticon** [comment]
**Another observation regarding the notification**

Starting point - Android and Desktop apps are connected and I've just completed a VR activity. Removed HMD.
Press blue Stop button in Android app. 
Close the Desktop app and SteamVR.

The android app notification remains persistant (not able to dismiss) until I toggle once more the Start/Stop process in android.

**Comment by ThomasGaubert** [comment]
Don't worry, this is a bug. 😁 The notification should go away when quitting the background service. The service publishes status updates to the notification which can end up creating the notification if it's attempting to update the notification during the shutdown process.

The next beta will include the fix!
