### ISSUE TITLE
v2.0 Not connected to WiFi

### ISSUE THREAD

**Issue by LilSleepyFox** [ThomasGaubert/zephyr#64]
Just set this up but getting a 'Not connected to WiFi warning' on the app. The steam app seems to work fine and says connected, and no problem scanning the QR code or using the join code.

I am using the Android Q beta, could that be having an effect?

[zephyr-logs.txt](https://github.com/ThomasGaubert/zephyr/files/3436308/zephyr-logs.txt)

Zephyr: 2.0.0-beta-f18f725
Device: Pixel 3 - Android Q Beta 5

**Comment by ThomasGaubert** [comment]
Thanks for the report! I'm running the Q beta and am seeing the same thing on my device 😟

Looks like [Q restricts WiFi connection status behind the location permission](https://developer.android.com/preview/privacy/camera-connectivity#fine-location-telephony-wifi-bt), so I'll need to update Zephyr to account for that.

**Comment by ThomasGaubert** [comment]
This is fixed in the latest beta release.I found another way to check WiFi status without requesting location permission. Thanks again for the report!
