### ISSUE TITLE
Launch Zephyr when launching VR

### ISSUE THREAD

**Issue by eschoenawa** [ThomasGaubert/zephyr#66]
I don't know if I'm missing something obvious, but I'd like to have Zephyr start when launching VR. Opening the Zephyr desktop app every time I want to go into VR is getting quite cumbersome.

**Comment by ThomasGaubert** [comment]
@eschoenawa I'm assuming this is for v1 right? Zephyr v2 will be distributed via Steam and will auto-register with SteamVR. You'll be able to control the auto start behavior from there.

![image](https://user-images.githubusercontent.com/406075/68732141-3704b280-0587-11ea-9131-acccee34950a.png)

**Comment by eschoenawa** [comment]
Good to know V2 will contain that feature. This can be closed then.
