### ISSUE TITLE
No way to select Ethernet Interface

### ISSUE THREAD

**Issue by FrankFromHR** [ThomasGaubert/zephyr#68]
I have multiple Ethernet Interfaces on my desktop however zephyr selected one by default which was the a vEthernet (DockerNAT) interface. I am able to have Zephyr connect to the correct interface but I have to disable my other interface before starting the applications. If there was an option to select this maybe even in a config file that would be helpful.

**Comment by ThomasGaubert** [comment]
Thanks for the report @FrankFromHR! This is addressed in Zephyr v2 (the desktop client will enumerate all network interfaces). Given that, I'll go ahead and close the issue out since v1 isn't planned to receive any more updates.
