### ISSUE TITLE
Zephyr Desktop App cannot sign in via Google

### ISSUE THREAD

**Issue by hackitfast** [ThomasGaubert/zephyr#83]
I'm able to login via Google from the Android app but I cannot login via the Windows desktop app.

> This browser or app may not be secure. Learn more
> 
> Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

![Zephyr_2020-04-12_21-51-29](https://user-images.githubusercontent.com/13812987/79085924-52c3de80-7d08-11ea-881b-769f202a7eae.png)

**Comment by ThomasGaubert** [comment]
@hackitfast - Thanks for the report! Unfortunately this is unlikely to be addressed as Zephyr v2 will be launching in the near future. The sync feature is replaced by a QR code that'll enable quick pairing.

Please reach out to me on Reddit (/u/TexasGamer) and I can hook you up with a beta key. 😄
